### ISSUE TITLE
تغییر کراولر

### ISSUE THREAD

**Issue by farhadhp** [rajabzz/digikala-crawler#3]
<div dir="rtl">
با سلام

الان اگه بخواهیم محصولات رو کراول کنیم باید کدوم قسمتو تغییر بدیم؟

با تشکر
</div>

**Comment by sshinoobi** [comment]
سلام،
کافیه توی فایل 
`digikala-crawler/DigikalaCrawler/spiders/comment_spider.py` 
توی متود
 `parse_product`  
خطی که گفته 
`response.follow` 
به پایینش رو انجام ندید و فقط مشخصات همون محصول رو 
yield 
کنید.
